package com.toxic.search;

final class ProfileStateMerger {
    static boolean update(ProfileResult target, ProfileResult incoming) {
        if (target == incoming) return true;
        if (incoming.snapshotVersion < target.snapshotVersion) return false;
        target.snapshotVersion = incoming.snapshotVersion;
        int friendsPage = target.friendsTabPage, badgesPage = target.badgesTabPage;
        int mottoIndex = target.previousMottosSlideIndex;
        boolean removed = target.friendsTabShowingRemoved, touched = target.friendsTabSelectionTouched;
        boolean hideAchievements = target.hideAchievementBadges;
        target.friendsLoadFailed = incoming.friendsLoadFailed; target.removedFriendsLoadFailed = incoming.removedFriendsLoadFailed; target.badgesLoadFailed = incoming.badgesLoadFailed;
        target.searchToken = incoming.searchToken;
        target.searchedNick = incoming.searchedNick;
        target.uniqueId = incoming.uniqueId;
        target.name = incoming.name;
        target.motto = incoming.motto;
        target.figure = incoming.figure;
        target.memberSince = incoming.memberSince;
        target.lastAccess = incoming.lastAccess;
        target.level = incoming.level;
        target.starGems = incoming.starGems;
        target.hotelKey = incoming.hotelKey;
        target.online = incoming.online;
        target.privateProfile = incoming.privateProfile;
        target.banned = incoming.banned;
        target.habboPublic = incoming.habboPublic;
        target.dex = incoming.dex;
        target.suggest = incoming.suggest;
        target.dexProfile = incoming.dexProfile;
        target.officialProfile = incoming.officialProfile;
        target.officialBadgeLookup = incoming.officialBadgeLookup;
        target.previousNames = incoming.previousNames;
        target.previousMottos = incoming.previousMottos;
        target.previousStyles = incoming.previousStyles;
        target.photos = incoming.photos;
        target.friends = incoming.friends;
        target.oldFriends = incoming.oldFriends;
        target.rooms = incoming.rooms;
        target.oldRooms = incoming.oldRooms;
        target.groups = incoming.groups;
        target.badges = incoming.badges;
        target.badgesWithAchievements = incoming.badgesWithAchievements;
        target.totalBadges = incoming.totalBadges;
        target.selectedBadges = incoming.selectedBadges;
        target.allPhotosSource = incoming.allPhotosSource;
        target.allStylesSource = incoming.allStylesSource;
        target.photosNextPage = incoming.photosNextPage;
        target.stylesNextPage = incoming.stylesNextPage;
        target.photosTotal = incoming.photosTotal;
        target.stylesTotal = incoming.stylesTotal;
        target.stylesRemoteNextPage = incoming.stylesRemoteNextPage;
        target.photosAutoLoadRetryAfterMs = incoming.photosAutoLoadRetryAfterMs;
        target.stylesAutoLoadRetryAfterMs = incoming.stylesAutoLoadRetryAfterMs;
        target.removedFriendsNextPage = incoming.removedFriendsNextPage;
        target.removedFriendsTotal = incoming.removedFriendsTotal;
        target.friendsNextPage = incoming.friendsNextPage;
        target.friendsTotal = incoming.friendsTotal;
        target.friendsTabPage = incoming.friendsTabPage;
        target.previousMottosSlideIndex = incoming.previousMottosSlideIndex;
        target.badgesNextPage = incoming.badgesNextPage;
        target.badgesTotal = incoming.badgesTotal;
        target.badgesTabPage = incoming.badgesTabPage;
        target.photosHasMore = incoming.photosHasMore;
        target.stylesHasMore = incoming.stylesHasMore;
        target.photosLoading = incoming.photosLoading;
        target.stylesLoading = incoming.stylesLoading;
        target.removedFriendsHasMore = incoming.removedFriendsHasMore;
        target.removedFriendsLoading = incoming.removedFriendsLoading;
        target.removedFriendsDataAvailable = incoming.removedFriendsDataAvailable;
        target.friendsHasMore = incoming.friendsHasMore;
        target.friendsLoading = incoming.friendsLoading;
        target.friendsPagedMode = incoming.friendsPagedMode;
        target.friendsTabShowingRemoved = incoming.friendsTabShowingRemoved;
        target.friendsTabSelectionTouched = incoming.friendsTabSelectionTouched;
        target.badgesHasMore = incoming.badgesHasMore;
        target.badgesLoading = incoming.badgesLoading;
        target.badgesPagedMode = incoming.badgesPagedMode;
        target.hideAchievementBadges = incoming.hideAchievementBadges;
        target.officialProfileAttempted = incoming.officialProfileAttempted;
        target.officialPhotosAttempted = incoming.officialPhotosAttempted;
        target.officialPhotosSucceeded = incoming.officialPhotosSucceeded;
        target.photosFromOfficial = incoming.photosFromOfficial;
        target.stylesFromComplement = incoming.stylesFromComplement;
        target.stylesRemotePaged = incoming.stylesRemotePaged;
        target.friendsDatesReady = incoming.friendsDatesReady;
        target.friendsTabPage = friendsPage;
        target.badgesTabPage = badgesPage;
        target.previousMottosSlideIndex = mottoIndex;
        if (touched) target.friendsTabShowingRemoved = removed;
        target.friendsTabSelectionTouched = touched;
        target.hideAchievementBadges = hideAchievements;
        return true;
    }
}
